package pageenscript2.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Accordion = 0;
  public static final int AccordionItems = 1;
  public static final int Alert = 2;
  public static final int AlertList = 3;
  public static final int Alerts = 4;
  public static final int Button = 5;
  public static final int Card = 6;
  public static final int CardDeck = 7;
  public static final int Cards = 8;
  public static final int Carousel = 9;
  public static final int CarouselItems = 10;
  public static final int Hero = 11;
  public static final int Item = 12;
  public static final int ItemList = 13;
  public static final int ListGroup = 14;
  public static final int ListItems = 15;
  public static final int Modal = 16;
  public static final int NavBar = 17;
  public static final int Page = 18;
  public static final int Program = 19;
  public static final int Seccion = 20;
  public static final int SeccionType = 21;
  public static final int Seccions = 22;
  public static final int StyleList = 23;
  public static final int Toast = 24;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL);
    builder.put(0x48b0f8fe545947f6L, Accordion);
    builder.put(0x48b0f8fe545947f1L, AccordionItems);
    builder.put(0x48b0f8fe5459478aL, Alert);
    builder.put(0x48b0f8fe545947e5L, AlertList);
    builder.put(0x48b0f8fe545947eaL, Alerts);
    builder.put(0x48b0f8fe5459477cL, Button);
    builder.put(0x48b0f8fe545947f9L, Card);
    builder.put(0x48b0f8fe54594806L, CardDeck);
    builder.put(0x48b0f8fe54594801L, Cards);
    builder.put(0x48b0f8fe545947e1L, Carousel);
    builder.put(0x48b0f8fe545947dcL, CarouselItems);
    builder.put(0x48b0f8fe545947a2L, Hero);
    builder.put(0x48b0f8fe545947c5L, Item);
    builder.put(0x48b0f8fe54594819L, ItemList);
    builder.put(0x48b0f8fe545947d4L, ListGroup);
    builder.put(0x48b0f8fe545947cfL, ListItems);
    builder.put(0x48b0f8fe54594768L, Modal);
    builder.put(0x48b0f8fe5459480aL, NavBar);
    builder.put(0x48b0f8fe54594766L, Page);
    builder.put(0x48b0f8fe54594760L, Program);
    builder.put(0x48b0f8fe545947b9L, Seccion);
    builder.put(0x48b0f8fe54594779L, SeccionType);
    builder.put(0x48b0f8fe545947c1L, Seccions);
    builder.put(0x48b0f8fe54594773L, StyleList);
    builder.put(0x48b0f8fe54594790L, Toast);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
