package pageenscript2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAccordion = createDescriptorForAccordion();
  /*package*/ final ConceptDescriptor myConceptAccordionItems = createDescriptorForAccordionItems();
  /*package*/ final ConceptDescriptor myConceptAlert = createDescriptorForAlert();
  /*package*/ final ConceptDescriptor myConceptAlertList = createDescriptorForAlertList();
  /*package*/ final ConceptDescriptor myConceptAlerts = createDescriptorForAlerts();
  /*package*/ final ConceptDescriptor myConceptButton = createDescriptorForButton();
  /*package*/ final ConceptDescriptor myConceptCard = createDescriptorForCard();
  /*package*/ final ConceptDescriptor myConceptCardDeck = createDescriptorForCardDeck();
  /*package*/ final ConceptDescriptor myConceptCards = createDescriptorForCards();
  /*package*/ final ConceptDescriptor myConceptCarousel = createDescriptorForCarousel();
  /*package*/ final ConceptDescriptor myConceptCarouselItems = createDescriptorForCarouselItems();
  /*package*/ final ConceptDescriptor myConceptHero = createDescriptorForHero();
  /*package*/ final ConceptDescriptor myConceptItem = createDescriptorForItem();
  /*package*/ final ConceptDescriptor myConceptItemList = createDescriptorForItemList();
  /*package*/ final ConceptDescriptor myConceptListGroup = createDescriptorForListGroup();
  /*package*/ final ConceptDescriptor myConceptListItems = createDescriptorForListItems();
  /*package*/ final ConceptDescriptor myConceptModal = createDescriptorForModal();
  /*package*/ final ConceptDescriptor myConceptNavBar = createDescriptorForNavBar();
  /*package*/ final ConceptDescriptor myConceptPage = createDescriptorForPage();
  /*package*/ final ConceptDescriptor myConceptProgram = createDescriptorForProgram();
  /*package*/ final ConceptDescriptor myConceptSeccion = createDescriptorForSeccion();
  /*package*/ final ConceptDescriptor myConceptSeccionType = createDescriptorForSeccionType();
  /*package*/ final ConceptDescriptor myConceptSeccions = createDescriptorForSeccions();
  /*package*/ final ConceptDescriptor myConceptStyleList = createDescriptorForStyleList();
  /*package*/ final ConceptDescriptor myConceptToast = createDescriptorForToast();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x71ee4433e2d941efL, 0xb4a9885e5d5aa8eaL, "pagegenscript");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAccordion, myConceptAccordionItems, myConceptAlert, myConceptAlertList, myConceptAlerts, myConceptButton, myConceptCard, myConceptCardDeck, myConceptCards, myConceptCarousel, myConceptCarouselItems, myConceptHero, myConceptItem, myConceptItemList, myConceptListGroup, myConceptListItems, myConceptModal, myConceptNavBar, myConceptPage, myConceptProgram, myConceptSeccion, myConceptSeccionType, myConceptSeccions, myConceptStyleList, myConceptToast);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Accordion:
        return myConceptAccordion;
      case LanguageConceptSwitch.AccordionItems:
        return myConceptAccordionItems;
      case LanguageConceptSwitch.Alert:
        return myConceptAlert;
      case LanguageConceptSwitch.AlertList:
        return myConceptAlertList;
      case LanguageConceptSwitch.Alerts:
        return myConceptAlerts;
      case LanguageConceptSwitch.Button:
        return myConceptButton;
      case LanguageConceptSwitch.Card:
        return myConceptCard;
      case LanguageConceptSwitch.CardDeck:
        return myConceptCardDeck;
      case LanguageConceptSwitch.Cards:
        return myConceptCards;
      case LanguageConceptSwitch.Carousel:
        return myConceptCarousel;
      case LanguageConceptSwitch.CarouselItems:
        return myConceptCarouselItems;
      case LanguageConceptSwitch.Hero:
        return myConceptHero;
      case LanguageConceptSwitch.Item:
        return myConceptItem;
      case LanguageConceptSwitch.ItemList:
        return myConceptItemList;
      case LanguageConceptSwitch.ListGroup:
        return myConceptListGroup;
      case LanguageConceptSwitch.ListItems:
        return myConceptListItems;
      case LanguageConceptSwitch.Modal:
        return myConceptModal;
      case LanguageConceptSwitch.NavBar:
        return myConceptNavBar;
      case LanguageConceptSwitch.Page:
        return myConceptPage;
      case LanguageConceptSwitch.Program:
        return myConceptProgram;
      case LanguageConceptSwitch.Seccion:
        return myConceptSeccion;
      case LanguageConceptSwitch.SeccionType:
        return myConceptSeccionType;
      case LanguageConceptSwitch.Seccions:
        return myConceptSeccions;
      case LanguageConceptSwitch.StyleList:
        return myConceptStyleList;
      case LanguageConceptSwitch.Toast:
        return myConceptToast;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAccordion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Accordion", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947f6L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405750");
    b.version(3);
    b.aggregate("accordion", 0x48b0f8fe545947f7L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947f1L).optional(false).ordered(true).multiple(false).origin("5237960137852405751").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAccordionItems() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "AccordionItems", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947f1L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405745");
    b.version(3);
    b.aggregate("item", 0x48b0f8fe545947f3L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947c5L).optional(true).ordered(true).multiple(true).origin("5237960137852405747").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAlert() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Alert", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459478aL);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405642");
    b.version(3);
    b.property("type", 0x48b0f8fe5459478cL).type(PrimitiveTypeId.STRING).origin("5237960137852405644").done();
    b.property("message", 0x48b0f8fe5459478dL).type(PrimitiveTypeId.STRING).origin("5237960137852405645").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAlertList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "AlertList", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947e5L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405733");
    b.version(3);
    b.aggregate("alert", 0x48b0f8fe545947e7L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459478aL).optional(true).ordered(true).multiple(true).origin("5237960137852405735").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAlerts() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Alerts", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947eaL);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405738");
    b.version(3);
    b.aggregate("alertList", 0x48b0f8fe545947ecL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947e5L).optional(false).ordered(true).multiple(false).origin("5237960137852405740").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForButton() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Button", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459477cL);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405628");
    b.version(3);
    b.property("text", 0x48b0f8fe54594780L).type(PrimitiveTypeId.STRING).origin("5237960137852405632").done();
    b.property("link", 0x48b0f8fe54594781L).type(PrimitiveTypeId.STRING).origin("5237960137852405633").done();
    b.property("color", 0x48b0f8fe54594783L).type(PrimitiveTypeId.STRING).origin("5237960137852405635").done();
    b.property("backgroundColor", 0x48b0f8fe54594785L).type(PrimitiveTypeId.STRING).origin("5237960137852405637").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCard() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Card", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947f9L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405753");
    b.version(3);
    b.property("title", 0x48b0f8fe545947fbL).type(PrimitiveTypeId.STRING).origin("5237960137852405755").done();
    b.property("text", 0x48b0f8fe545947fcL).type(PrimitiveTypeId.STRING).origin("5237960137852405756").done();
    b.aggregate("button", 0x48b0f8fe545947ffL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459477cL).optional(true).ordered(true).multiple(false).origin("5237960137852405759").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCardDeck() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "CardDeck", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594806L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405766");
    b.version(3);
    b.aggregate("cards", 0x48b0f8fe54594808L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594801L).optional(false).ordered(true).multiple(false).origin("5237960137852405768").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCards() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Cards", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594801L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405761");
    b.version(3);
    b.aggregate("tarjeta", 0x48b0f8fe54594803L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947f9L).optional(true).ordered(true).multiple(true).origin("5237960137852405763").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCarousel() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Carousel", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947e1L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405729");
    b.version(3);
    b.aggregate("carouselItems", 0x48b0f8fe545947e3L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947dcL).optional(false).ordered(true).multiple(false).origin("5237960137852405731").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCarouselItems() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "CarouselItems", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947dcL);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405724");
    b.version(3);
    b.property("title", 0x2850591c29057719L).type(PrimitiveTypeId.STRING).origin("2904919737136150297").done();
    b.property("content", 0x2850591c2905771aL).type(PrimitiveTypeId.STRING).origin("2904919737136150298").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHero() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Hero", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947a2L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405666");
    b.version(3);
    b.property("backgroundColor", 0x48b0f8fe545947a4L).type(PrimitiveTypeId.STRING).origin("5237960137852405668").done();
    b.property("title", 0x48b0f8fe545947a6L).type(PrimitiveTypeId.STRING).origin("5237960137852405670").done();
    b.property("subtitle", 0x48b0f8fe545947a9L).type(PrimitiveTypeId.STRING).origin("5237960137852405673").done();
    b.aggregate("button", 0x48b0f8fe545947b6L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459477cL).optional(true).ordered(true).multiple(false).origin("5237960137852405686").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Item", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947c5L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405701");
    b.version(3);
    b.property("title", 0x48b0f8fe545947c7L).type(PrimitiveTypeId.STRING).origin("5237960137852405703").done();
    b.aggregate("styleList", 0x48b0f8fe545947c9L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594773L).optional(true).ordered(true).multiple(false).origin("5237960137852405705").done();
    b.aggregate("seccions", 0x48b0f8fe545947ccL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947c1L).optional(true).ordered(true).multiple(false).origin("5237960137852405708").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForItemList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "ItemList", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594819L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405785");
    b.version(3);
    b.aggregate("item", 0x48b0f8fe5459481bL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947c5L).optional(true).ordered(true).multiple(true).origin("5237960137852405787").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListGroup() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "ListGroup", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947d4L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405716");
    b.version(3);
    b.aggregate("listItems", 0x48b0f8fe545947d6L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947cfL).optional(false).ordered(true).multiple(false).origin("5237960137852405718").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForListItems() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "ListItems", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947cfL);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405711");
    b.version(3);
    b.aggregate("item", 0x48b0f8fe545947d1L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947c5L).optional(true).ordered(true).multiple(true).origin("5237960137852405713").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForModal() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Modal", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594768L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405608");
    b.version(3);
    b.property("id", 0x48b0f8fe5459476dL).type(PrimitiveTypeId.STRING).origin("5237960137852405613").done();
    b.property("title", 0x48b0f8fe5459476eL).type(PrimitiveTypeId.STRING).origin("5237960137852405614").done();
    b.property("body", 0x48b0f8fe54594771L).type(PrimitiveTypeId.STRING).origin("5237960137852405617").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNavBar() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "NavBar", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459480aL);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405770");
    b.version(3);
    b.property("backgroundColor", 0x48b0f8fe5459480cL).type(PrimitiveTypeId.STRING).origin("5237960137852405772").done();
    b.aggregate("listItems", 0x48b0f8fe5459480fL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947cfL).optional(false).ordered(true).multiple(false).origin("5237960137852405775").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Page", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594766L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405606");
    b.version(3);
    b.property("title", 0x48b0f8fe54594814L).type(PrimitiveTypeId.STRING).origin("5237960137852405780").done();
    b.aggregate("style", 0x2850591c28f888ecL).target(0x71ee4433e2d941efL, 0xb4a9885e5d5aa8eaL, 0x48b0f8fe54594773L).optional(false).ordered(true).multiple(false).origin("2904919737135302892").done();
    b.aggregate("sections", 0x48b0f8fe54594817L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594779L).optional(false).ordered(true).multiple(true).origin("5237960137852405783").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForProgram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Program", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594760L);
    b.class_(false, false, true);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405600");
    b.version(3);
    b.aggregate("page", 0x48b0f8fe54594820L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594766L).optional(false).ordered(true).multiple(false).origin("5237960137852405792").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSeccion() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Seccion", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947b9L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405689");
    b.version(3);
    b.property("type", 0x48b0f8fe545947bbL).type(PrimitiveTypeId.STRING).origin("5237960137852405691").done();
    b.aggregate("seccionType", 0x48b0f8fe545947bdL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594779L).optional(true).ordered(true).multiple(false).origin("5237960137852405693").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSeccionType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "SeccionType", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594779L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405625");
    b.version(3);
    b.aggregate("navBar", 0x48b0f8fe54594822L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe5459480aL).optional(true).ordered(true).multiple(false).origin("5237960137852405794").done();
    b.aggregate("hero", 0x48b0f8fe54594824L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947a2L).optional(true).ordered(true).multiple(false).origin("5237960137852405796").done();
    b.aggregate("cardDeck", 0x48b0f8fe54594826L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594806L).optional(true).ordered(true).multiple(false).origin("5237960137852405798").done();
    b.aggregate("accordion", 0x48b0f8fe54594828L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947f6L).optional(true).ordered(true).multiple(false).origin("5237960137852405800").done();
    b.aggregate("alerts", 0x48b0f8fe5459482aL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947eaL).optional(true).ordered(true).multiple(false).origin("5237960137852405802").done();
    b.aggregate("modal", 0x48b0f8fe5459482cL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594768L).optional(true).ordered(true).multiple(false).origin("5237960137852405804").done();
    b.aggregate("carousel", 0x48b0f8fe5459482eL).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947e1L).optional(true).ordered(true).multiple(false).origin("5237960137852405806").done();
    b.aggregate("listGroup", 0x48b0f8fe54594830L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947d4L).optional(true).ordered(true).multiple(false).origin("5237960137852405808").done();
    b.aggregate("toast", 0x48b0f8fe54594832L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594790L).optional(true).ordered(true).multiple(false).origin("5237960137852405810").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSeccions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Seccions", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947c1L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405697");
    b.version(3);
    b.aggregate("seccion", 0x48b0f8fe545947c3L).target(0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe545947b9L).optional(true).ordered(true).multiple(false).origin("5237960137852405699").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStyleList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "StyleList", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594773L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405619");
    b.version(3);
    b.property("primaryColor", 0x48b0f8fe54594775L).type(PrimitiveTypeId.STRING).origin("5237960137852405621").done();
    b.property("secondaryColor", 0x48b0f8fe54594777L).type(PrimitiveTypeId.STRING).origin("5237960137852405623").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForToast() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("pageenscript2", "Toast", 0xccc77a9e69584a98L, 0xa8364a20ed0f063aL, 0x48b0f8fe54594790L);
    b.class_(false, false, false);
    b.origin("r:153d6e45-b8da-4785-9f1a-e424baeaca4c(pageenscript2.structure)/5237960137852405648");
    b.version(3);
    b.property("id", 0x48b0f8fe54594792L).type(PrimitiveTypeId.STRING).origin("5237960137852405650").done();
    b.property("title", 0x48b0f8fe54594793L).type(PrimitiveTypeId.STRING).origin("5237960137852405651").done();
    b.property("message", 0x48b0f8fe54594795L).type(PrimitiveTypeId.STRING).origin("5237960137852405653").done();
    b.property("delay", 0x48b0f8fe54594798L).type(PrimitiveTypeId.INTEGER).origin("5237960137852405656").done();
    return b.create();
  }
}
